server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-oss

aliyun:
  oss:
    endpoint: "oss-cn-shenzhen.aliyuncs.com"
    KeyId: "LTAI5tJihxRWcj2ru8gMonWe"
    KeySecret: "qTV3PtKcDir5BsxsVI85hTDCQTKy5O"
    bucketName: "wangping-bucket-img"
